export const bandPics = [
  // {
  //   id: 0,
  //   src: "",
  //   alt: "",
  //   width: 0,  
  //   height: 0,
  //   orientation: "",
  // },
  {
    id: 1,
    src: "/images/performance-pics/band/lofi-cherokee-1.jpg",
    alt: "po performing at Free 4 All",
    width: 1563,  
    height: 2048,
    orientation: "portrait",
  },
  {
    id: 2,
    src: "/images/performance-pics/band/lofi-cherokee-2.jpg",
    alt: "",
    width: 2030,  
    height: 2048,
    orientation: "portrait",
  },
  {
    id: 3,
    src: "/images/performance-pics/band/po-band-venice.jpg",
    alt: "",
    width: 964,  
    height: 771,
    orientation: "landscape",
  },
  {
    id: 4,
    src: "/images/performance-pics/band/po-mia-city-hall.png",
    alt: "",
    width: 6000,  
    height: 4000,
    orientation: "landscape",
  },
  {
    id: 5,
    src: "/images/performance-pics/band/po-mia-free-4-all.jpg",
    alt: "po-mia-free-4-all.jpg",
    width: 7008,  
    height: 4672,
    orientation: "landscape",
  },
  {
    id: 6,
    src: "/images/performance-pics/band/po-with-brawsh.jpg",
    alt: "",
    width: 960,  
    height: 706,
    orientation: "landscape",
  },
  {
    id: 7,
    src: "/images/performance-pics/band/po-with-bren.jpg",
    alt: "",
    width: 2070,  
    height: 2070,
    orientation: "landscape",
  },
  {
    id: 8,
    src: "/images/performance-pics/band/twangfest.jpg",
    alt: "",
    width: 3000,  
    height: 2400,
    orientation: "landscape",
  },
  {
    id: 9,
    src: "/images/performance-pics/band/venice-ensemble.jpg",
    alt: "",
    width: 828,  
    height: 620,
    orientation: "landscape",
  }
]