export const finalPics = [
  {
    id: 1,
    src: "/images/final-webp/free-4-all.webp",
    alt: "po performing at Free 4 All",
    width: 939,  
    height: 939,
    orientation: "square",
  },
  {
    id: 2,
    src: "/images/final-webp/guitar-future-bright.webp",
    alt: "",
    width: 1708,  
    height: 1366,
    orientation: "landscape",
  },
  {
    id: 3,
    src: "/images/final-webp/guitar-headstock.webp",
    alt: "",
    width: 5454,  
    height: 5454,
    orientation: "square",
  },
  {
    id: 4,
    src: "/images/final-webp/guitar-logo.webp",
    alt: "",
    width: 5369,  
    height: 5369,
    orientation: "square",
  },
   {
    id: 5,
    src: "/images/final-webp/guitar-playing.webp",
    alt: "",
    width: 5234,  
    height: 7328,
    orientation: "portrait",
  },
  {
    id: 6,
    src: "/images/final-webp/guitar-pout.webp",
    alt: "",
    width: 6830,  
    height: 5464,
    orientation: "landscape",
  },
  {
    id: 7,
    src: "/images/final-webp/guitar-smiling.webp",
    alt: "",
    width: 5101,  
    height: 7142,
    orientation: "portrait",
  },
  {
    id: 8,
    src: "/images/final-webp/headshot.webp",
    alt: "",
    width: 3998,  
    height: 3998,
    orientation: "square",
  },
  {
    id: 9,
    src: "/images/final-webp/heavy-anchor.webp",
    alt: "",
    width: 4344,  
    height: 5784,
    orientation: "portrait",
  },
  {
    id: 10,
    src: "/images/final-webp/kaleidoscope-po.webp",
    alt: "",
    width: 2912,  
    height: 4368,
    orientation: "portrait",
  },
  {
    id: 11,
    src: "/images/final-webp/po-slso.webp",
    alt: "",
    width: 1667,  
    height: 2500,
    orientation: "portrait",
  },
  {
    id: 12,
    src: "/images/final-webp/po-tiny-guitar.webp",
    alt: "",
    width: 814,  
    height: 1148,
    orientation: "portrait",
  },
];