export const finalPics = [
  {
    id: 1,
    src: "/images/final-pics/free-4-all.png",
    alt: "po performing at Free 4 All",
    width: 939,  
    height: 939,
    orientation: "square",
  },
  {
    id: 2,
    src: "/images/final-pics/guitar-future-bright-25.png",
    alt: "",
    width: 1708,  
    height: 1366,
    orientation: "landscape",
  },
  {
    id: 3,
    src: "/images/final-pics/guitar-headstock.jpg",
    alt: "",
    width: 5454,  
    height: 5454,
    orientation: "square",
  },
  {
    id: 4,
    src: "/images/final-pics/guitar-logo.jpg",
    alt: "",
    width: 5369,  
    height: 5369,
    orientation: "square",
  },
   {
    id: 5,
    src: "/images/final-pics/guitar-playing.jpg",
    alt: "",
    width: 5234,  
    height: 7328,
    orientation: "portrait",
  },
  {
    id: 6,
    src: "/images/final-pics/guitar-pout.jpg",
    alt: "",
    width: 6830,  
    height: 5464,
    orientation: "landscape",
  },
  {
    id: 7,
    src: "/images/final-pics/guitar-smiling.jpg",
    alt: "",
    width: 5101,  
    height: 7142,
    orientation: "portrait",
  },
  {
    id: 8,
    src: "/images/final-pics/headshot.jpg",
    alt: "",
    width: 3998,  
    height: 3998,
    orientation: "square",
  },
  {
    id: 9,
    src: "/images/final-pics/heavy-anchor.jpg",
    alt: "",
    width: 4344,  
    height: 5784,
    orientation: "portrait",
  },
  {
    id: 10,
    src: "/images/final-pics/kaleidoscope-po.jpg",
    alt: "",
    width: 2912,  
    height: 4368,
    orientation: "portrait",
  },
  
 
  {
    id: 11,
    src: "/images/final-pics/po-slso.jpg",
    alt: "",
    width: 1667,  
    height: 2500,
    orientation: "portrait",
  },
  {
    id: 12,
    src: "/images/final-pics/po-tiny-guitar.jpg",
    alt: "",
    width: 814,  
    height: 1148,
    orientation: "portrait",
  },
];