export const pics = [
  {
    id: 1,
    src: "/images/free-4-all.webp",
    alt: "po performing at Free 4 All",
    width: 2102,
    height: 1401,
    orientation: "landscape",
  },
  {
    id: 2,
    src: "/images/infinite-spectrum.webp",
    alt: "po in a rainbow skirt",
    width: 710,
    height: 1065,
    orientation: "portrait",
  },
  {
    id: 3,
    src: "/images/ghost.png",
    alt: "Photo 3",
    width: 1184,
    height: 1776,
    orientation: "portrait",
  },
  {
    id: 4,
    src: "/images/po.webp",
    alt: "po mia",
    width: 1200,
    height: 1800,
    orientation: "portrait",
  },
  {
    id: 5,
    src: "/images/po-elec-guitar.webp",
    alt: "Photo 3",
    width: 725,
    height: 1152,
    orientation: "portrait",
  },
  {
    id: 6,
    src: "/images/po-hearts.webp",
    alt: "po surrounded by hearts",
    width: 2664,
    height: 1902,
    orientation: "landscape",
  },
  {
    id: 7,
    src: "/images/po-in-chair.webp",
    alt: "po in a chair playing guitar outside",
    width: 942,
    height: 1244,
    orientation: "portrait",
  },
  {
    id: 8,
    src: "/images/po-city-hall.webp",
    alt: "po playing at city hall with band",
    width: 1920,
    height: 1280,
    orientation: "landscape",
  },
  {
    id: 9,
    src: "/images/po-no-bg.png",
    alt: "po with no background",
    width: 1184,
    height: 1776,
    orientation: "portrait",
  },
  {
    id: 10,
    src: "/images/po-on-frog.webp",
    alt: "po sitting on a frog sculputure outside of the Venice Cafe in St. Louis, MO",
    width: 768,
    height: 1024,
  orientation: "portrait",
  },
  {
    id: 11,
    src: "/images/po-on-stairs.webp",
    alt: "po standing on a fancy staircase",
    width: 947,
    height: 1421,
    orientation: "portrait",
  },
  {
    id: 12,
    src: "/images/po-tiny-guitar.webp",
    alt: "po seated playing a small guitar",
    width: 814,
    height: 1148,
    orientation: "portrait",
  },
  {
    id: 13,
    src: "/images/po-venice-cafe.webp",
    alt: "po playing at the Venice Cafe in St. Louis, Missouri",
    width: 1217,
    height: 956,
    orientation: "landscape",
  },
  {
    id: 14,
    src: "/images/twangfest.webp",
    alt: "po playing with the band at Twangfest",
    width: 1980,
    height: 1584,
    orientation: "landscape",
  },
];
