export const promoPics = [
  {
    id: 0,
    src: "/images/promo-pics/infinite-spectrum.jpg",
    alt: "promo image 1",
    width: 1184,  
    height: 1776,
    orientation: "portrait",
  },
    {
    id: 1,
    src: "/images/promo-pics/lofi-cherokee.jpg",
    alt: "promo image 2",
    width: 2703,  
    height: 3000,
    orientation: "portrait",
  },
    {
    id: 2,
    src: "/images/promo-pics/pocaster.jpg",
    alt: "promo image 3",
    width: 869,  
    height: 1440,
    orientation: "portrait",
  },
    {
    id: 3,
    src: "/images/promo-pics/po-on-frog.jpg",
    alt: "promo image 4",
    width: 768,  
    height: 1024,
    orientation: "portrait",
  },
    {
    id: 4,
    src: "/images/promo-pics/po-playing.jpg",
    alt: "promo image 5",
    width: 906,  
    height: 1440,
    orientation: "portrait",
  },
    {
    id: 5,
    src: "/images/promo-pics/po-n-roses.jpg",
    alt: "promo image 6",
    width: 1612,  
    height: 2237,
    orientation: "portrait",
  },
]