export const soloPics = [
  {
    id: 0,
    src: "/images/performance-pics/solo/duckroom-1.jpg",
    alt: "po performing solo at The Duck Room",
    width: 4000,  
    height: 6000,
    orientation: "portrait",
  },
  {
    id: 1,
    src: "/images/performance-pics/solo/duckroom-2.jpg",
    alt: "po performing solo at The Duck Room",
    width: 4000,  
    height: 6000,
    orientation: "portrait",
  },
  {
    id: 2,
    src: "/images/performance-pics/solo/heavy-anchor.jpg",
    alt: "po performing solo at The Heavy Anchor",
    width: 4344,  
    height: 5784,
    orientation: "portrait",
  },
  {
    id: 3,
    src: "/images/performance-pics/solo/sqsh.jpg",
    alt: "po performing solo outside in a park",
    width: 2354,  
    height: 3108,
    orientation: "portrait",
  },
  {
    id: 4,
    src: "/images/performance-pics/solo/venice-cafe-1.jpg",
    alt: "po performing solo at The Venice Cafe",
    width: 1738,  
    height: 1365,
    orientation: "landscape",
  },
  {
    id: 5,
    src: "/images/performance-pics/solo/venice-cafe-2.jpg",
    alt: "po performing solo at The Venice Cafe",
    width: 1330,  
    height: 1365,
    orientation: "portrait",
  },
]